name: publish

on: [push]

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build, test, and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/amine7777/parser:latest
          docker build . --tag $IMAGE_NAME
          docker run $IMAGE_NAME
          docker push $IMAGE_NAME